### ISSUE TITLE
Error during build, conflict when tagging

### ISSUE THREAD

**Issue by geoffroyjabouley** [6si/shipwright#11]
Hello

since i upgrade docker to v1.4.1, shipwright has hard time building all my images WHEN there is already built images on the local docker repository.

Example:
after a failed build, i have the following images:
```
REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
test/image2                  1da5115d0349        fcdf35f64a13        15 hours ago        390.2 MB
test/image1                  1da5115d0349        cb66ae0c4a38        16 hours ago        560.1 MB
test/image0                  1da5115d0349        a0ca4de9ff4c        16 hours ago        109.7 MB
debian                       stable              8633fa92ce62        5 weeks ago         85.1 MB
```

When i restart the build, i get the following error:
```
$ shipwright test
Traceback (most recent call last):
  File "/usr/local/bin/shipwright", line 9, in <module>
    load_entry_point('shipwright==0.0.2', 'console_scripts', 'shipwright')()
  File "/usr/local/lib/python2.7/dist-packages/shipwright/cli.py", line 63, in main
    for t, docker_commit in Shipwright(namespace,repo,client).build(highlight):
  File "/usr/local/lib/python2.7/dist-packages/shipwright/__init__.py", line 75, in build
    this_ref_str
  File "/usr/local/lib/python2.7/dist-packages/shipwright/docker.py", line 47, in tag_containers
    tag=tag
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 1003, in tag
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 89, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict: Tag 1da5115d0349 is already set to image a0ca4de9ff4c2bbfd111ada42168263fc515276e93adf251c1621668bd98de2b, if you want to replace it, please use -f option")
```

A solution that seems to solve this issue if using the force flag of the docker client tag function
https://github.com/6si/shipwright/blob/master/shipwright/docker.py#L47

Before
```python
client.tag(
container.name + ":" + container.last_built_ref,
container.name,
tag=tag
)
```

After
```python
client.tag(
container.name + ":" + container.last_built_ref,
container.name,
tag=tag,
force=True
)
```

**Comment by srobertson** [comment]
Thanks for the tip! Latest version of shipwright 0.2.1 has your fix.
