### ISSUE TITLE
Cannot build with boot2docker on OSX

### ISSUE THREAD

**Issue by remyhonig** [6si/shipwright#13]
When running ```shipwright build``` on OSX with boot2docker I get the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/shipwright", line 9, in <module>
    load_entry_point('shipwright==0.2.1', 'console_scripts', 'shipwright')()
  File "/Library/Python/2.7/site-packages/shipwright/cli.py", line 190, in main
    for event in command(*args):
  File "/Library/Python/2.7/site-packages/shipwright/__init__.py", line 76, in build
    tree = dependencies.eval(specifiers, self.targets())
  File "/Library/Python/2.7/site-packages/shipwright/__init__.py", line 48, in targets
    docker.tags_from_containers(self.docker_client, containers)  # list of tags
  File "/Library/Python/2.7/site-packages/shipwright/fn.py", line 40, in curry_
    return f(*chain(args, a), **k)
  File "/Library/Python/2.7/site-packages/shipwright/docker.py", line 36, in tags_from_containers
    containers
  File "/Library/Python/2.7/site-packages/shipwright/fn.py", line 56, in compose_
    return reduce(lambda v, f: f(v), ordered, v)
  File "/Library/Python/2.7/site-packages/shipwright/fn.py", line 56, in <lambda>
    return reduce(lambda v, f: f(v), ordered, v)
  File "/Library/Python/2.7/site-packages/shipwright/fn.py", line 40, in curry_
    return f(*chain(args, a), **k)
  File "/Library/Python/2.7/site-packages/shipwright/docker.py", line 29, in last_built_from_docker
    )(client.images(name))
  File "/Library/Python/2.7/site-packages/docker/client.py", line 638, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/Library/Python/2.7/site-packages/docker/client.py", line 81, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname '192.168.59.103' doesn't match 'boot2docker'
```

```boot2docker ip``` gives 192.168.59.103

```
Boot2Docker-cli version: v1.4.1 
Git commit: 43241cb
```

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by srobertson** [comment]
With boot2docker:

Either use the `--x-assert-hostname` when running the command as in:

`shipwright --x-assert-hostname`

Or in your .shipwright.json file add this line.

{
...
 assert_hostname: False
}

**Comment by remyhonig** [comment]
Thanks!

**Comment by dunk** [comment]
To save the next person the bother, the code you need to add is actually:

"assert_hostname": false
