### ISSUE TITLE
folder naming issues

### ISSUE THREAD

**Issue by dayer4b** [6si/shipwright#16]
I just went through some debugging hell with shipwright running on a Jenkins slave.  I was trying to get it to build images from a project, but the Jenkins "project name" was not the same as git project name (kind of a long story).  

So, the folder ended up being "Test" (with the capital T).  Shipwright failed on this in a fairly unfriendly way:

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/shipwright", line 9, in <module>
    load_entry_point('shipwright==0.2.2', 'console_scripts', 'shipwright')()
  File "/usr/local/lib/python2.7/dist-packages/shipwright/cli.py", line 193, in main
    for event in command(*args):
  File "/usr/local/lib/python2.7/dist-packages/shipwright/__init__.py", line 101, in build_tree
    targets # what needs building
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 295, in _stream_helper
    assert reader._fp.chunked
AssertionError
```

Which led me on a wild goose chase.  I eventually found the issue and switched the Jenkins Git settings to clone to a sub directory by the name of the git project.  

It seems that uppercase folder names cause errors.  I understand that the "names" property in `.shipwright.json` can be used to fix this by mapping paths to Docker repository names, but the naming restriction should be documented.

I guess that the git project name could be culled from the remotes, but there's no guarantee that there will be any remotes.  Documentation would nice, though :)

**Comment by srobertson** [comment]
Sorry you had so much grief!

Happy to document it as soon as I understand why it failed. I don't know of any naming restrictions.

Can you post your folder structure, directory names along with steps to reproduce this failure?

**Comment by dayer4b** [comment]
Sorry for the delay.  

Steps to reproduce the issue:

```bash
~$ mkdir shipwrightTest
~$ cd shipwrightTest
~$ git init
~$ printf "FROM busybox\nADD . /code" > Dockerfile
~$ printf '{\n  "version": 1.0,\n  "namespace": "shipwright"\n}' > .shipwright.json
~$ git add .
~$ git commit -a -m 'initial commit'
[master (root-commit) b867619] initial commit
 2 files changed, 6 insertions(+)
 create mode 100644 .shipwright.json
 create mode 100644 Dockerfile
~$ shipwright
Traceback (most recent call last):
  File "/usr/local/bin/shipwright", line 9, in <module>
    load_entry_point('shipwright==0.2.2', 'console_scripts', 'shipwright')()
  File "/usr/local/lib/python2.7/dist-packages/shipwright/cli.py", line 193, in main
    for event in command(*args):
  File "/usr/local/lib/python2.7/dist-packages/shipwright/__init__.py", line 101, in build_tree
    targets # what needs building
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 295, in _stream_helper
    assert reader._fp.chunked
AssertionError
```

Whereas, if you initially create the folder as `shipwrighttest` or something, it works fine.

**Comment by srobertson** [comment]
I just posted a bugfix that may be the root of this issue as well.

I haven't tested with your example yet. Hope to do that soon.

**Comment by srobertson** [comment]
Assuming this was fixed

**Comment by dayer4b** [comment]
Sorry I wasn't paying attention when this issue was addressed, but it still looks like a problem.  I'm testing with the latest version, v0.6.3, on a Mac running 10.11.6

I put together a simple script that runs the test.  It's basically the same as before:

https://gist.github.com/dayer4b/665ec4aa46f3945dc5a810138be923c9

when using the camel-cased folder name, the output is:

```bash
Initialized empty Git repository in /private/tmp/shipwrightTest/.git/
[master (root-commit) 2b8c7f4] initial commit
 2 files changed, 6 insertions(+)
 create mode 100644 .shipwright.json
 create mode 100644 Dockerfile
Traceback (most recent call last):
  File "/usr/local/bin/shipwright", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/shipwright/cli.py", line 183, in main
    new_style_args=arguments,
  File "/usr/local/lib/python2.7/site-packages/shipwright/cli.py", line 270, in run
    for event in events:
  File "/usr/local/lib/python2.7/site-packages/shipwright/base.py", line 25, in _build
    for evt in build.do_build(client, ref, targets, pull_cache):
  File "/usr/local/lib/python2.7/site-packages/shipwright/build.py", line 42, in do_build
    for evt in build(client, parent_ref, target, pull_cache):
  File "/usr/local/lib/python2.7/site-packages/shipwright/build.py", line 95, in build
    for evt in build_evts:
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 268, in _stream_helper
    yield self._result(response, json=decode)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error parsing reference: "shipwright/shipwrightTest:2b8c7f496d35" is not a valid repository/tag")
```

when using the all lowercase folder name, the output is:

```bash
Initialized empty Git repository in /private/tmp/shipwrighttest/.git/
[master (root-commit) 9b1ecb9] initial commit
 2 files changed, 6 insertions(+)
 create mode 100644 .shipwright.json
 create mode 100644 Dockerfile
shipwright/shipwrighttest | Step 1 : FROM busybox
shipwright/shipwrighttest |  ---> e02e811dd08f
shipwright/shipwrighttest | Step 2 : ADD . /code
shipwright/shipwrighttest |  ---> 648244d42f55
shipwright/shipwrighttest | Removing intermediate container 30fd8a3f8029
shipwright/shipwrighttest | Successfully built 648244d42f55
Tagging shipwright/shipwrighttest:9b1ecb9ccd32 to shipwright/shipwrighttest:master
Tagging shipwright/shipwrighttest:9b1ecb9ccd32 to shipwright/shipwrighttest:latest
Tagging shipwright/shipwrighttest:9b1ecb9ccd32 to shipwright/shipwrighttest:9b1ecb9ccd32
```

**Comment by graingert** [comment]
perhaps we should fail fast with invalid docker names

**Comment by dayer4b** [comment]
oh, i see.  https://docs.docker.com/engine/reference/commandline/tag/

I didn't realize that was a docker limitation.  They say that Names cannot have uppercase, but tags may.  I suppose a friendly failure message would suffice
