### ISSUE TITLE
Issue with 'shipwright build' and Docker version 1.12.0, build 8eab29e

### ISSUE THREAD

**Issue by kgpayne** [6si/shipwright#77]
▶ shipwright build
Traceback (most recent call last):
  File "/Users/user/anaconda/bin/shipwright", line 11, in <module>
    sys.exit(main())
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/cli.py", line 170, in main
    environ=os.environ,
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/cli.py", line 243, in run
    for event in events:
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/base.py", line 22, in _build
    for evt in build.do_build(self.docker_client, this_ref_str, targets):
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/build.py", line 42, in do_build
    for evt in build(client, parent_ref, target):
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/build.py", line 63, in build
    built_tags = docker.last_built_from_docker(client, image.name)
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/docker.py", line 28, in last_built_from_docker
    return list([x for i in images for x in key_from_image_info(i)])
  File "/Users/user/anaconda/lib/python2.7/site-packages/shipwright/docker.py", line 23, in key_from_image_info
    return [key_from_image_name(t) for t in image_info_dict['RepoTags']]
TypeError: 'NoneType' object is not iterable

**Comment by graingert** [comment]
Can you reproduce on 3.5 without using anaconda?

**Comment by kgpayne** [comment]
▶ shipwright build
Traceback (most recent call last):
  File "/Users/user/Projects/life_organiser/venv3/bin/shipwright", line 11, in <module>
    sys.exit(main())
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/cli.py", line 170, in main
    environ=os.environ,
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/cli.py", line 243, in run
    for event in events:
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/base.py", line 22, in _build
    for evt in build.do_build(self.docker_client, this_ref_str, targets):
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/build.py", line 42, in do_build
    for evt in build(client, parent_ref, target):
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/build.py", line 63, in build
    built_tags = docker.last_built_from_docker(client, image.name)
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py", line 28, in last_built_from_docker
    return list([x for i in images for x in key_from_image_info(i)])
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py", line 28, in <listcomp>
    return list([x for i in images for x in key_from_image_info(i)])
  File "/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py", line 23, in key_from_image_info
    return [key_from_image_name(t) for t in image_info_dict['RepoTags']]
TypeError: 'NoneType' object is not iterable
(venv3)

**Comment by graingert** [comment]
can you send me the directory you're running on?

**Comment by kgpayne** [comment]
It's a work in progress at the moment, so still has secret access keys etc. in a local git repo. I'd prefer not to send the whole lot over if thats ok?

**Comment by graingert** [comment]
@kgpayne sure, can you make a minimal failing example

**Comment by kgpayne** [comment]
@graingert Thanks for taking a look :)
https://github.com/kgpayne/shipwright_example

Confirmed still broken in same 3.5 venv as above.

**Comment by graingert** [comment]
@danpalmer is this the same OS X issue you're having in https://github.com/graingert/dockhand/pull/4/files

**Comment by graingert** [comment]
I can't repeat this, can you edit

/Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py
and apply this patch:

```patch
--- /Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py 2016-08-11 18:05:28.716161012 +0100
+++ /Users/user/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py	2016-08-11 18:12:57.744051651 +0100
@@ -25,6 +25,8 @@
 
 def last_built_from_docker(client, name):
     images = client.images(name)
+    import pprint
+    pprint.pprint(images)
     return list([x for i in images for x in key_from_image_info(i)])
```

and tell me what you get?

**Comment by graingert** [comment]
basically it looks like the docker API call in client.images(name) is returning a None in the list.

**Comment by kgpayne** [comment]
Ha! Small world :) I was in ECS from 2009 - 2014 (MEng Electronic Engineering). Work is near Bank station, home is near Clapham Junction. Happy to meet up some time next week if it helps?

**Comment by kgpayne** [comment]
shipwright build
[{'Created': 1470670579,
  'Id': 'sha256:8ea2913993a7c1b69f81ce8c3d20e27f2ee4d50bb1d697f1439f25d1556ecfe9',
  'Labels': {},
  'ParentId': 'sha256:372859dd1c695759fe765be375346390ddd393f76fa84319630d1d64b85b9806',
  'RepoDigests': None,
  'RepoTags': ['108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb:218ba77a4b55',
               '108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb:59c44e5ee129',
               '108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb:f664a467b118'],
  'Size': 311023415,
  'VirtualSize': 311023415}]
108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb | Step 1 : FROM java:8-jre
108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb |  ---> 372859dd1c69
108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb | Step 2 : ENTRYPOINT java -Djava.library.path=./DynamoDBLocal_lib -jar /dynamodb/DynamoDBLocal.jar -sharedDb -port 5000 -dbPath /dynamodb/
108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb |  ---> Using cache
108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb |  ---> 8ea2913993a7
108747154147.dkr.ecr.eu-west-1.amazonaws.com/dynamodb | Successfully built 8ea2913993a7
[{'Created': 1470825033,
  'Id': 'sha256:dbdc32378da9108d516ee51a64d7d1f6ab826e319c47a11d17699b2ea433380b',
  'Labels': {},
  'ParentId': 'sha256:86a3381f932e6968ebccd54dcad098d99c7aa1dfd694a0080700a7aa6e3ea114',
  'RepoDigests': ['108747154147.dkr.ecr.eu-west-1.amazonaws.com/life.organised@sha256:c9feed44356e1450b83d248e0ce9123eb341a6c6b14a4448746fdff85ac9b474'],
  'RepoTags': ['108747154147.dkr.ecr.eu-west-1.amazonaws.com/life.organised:latest'],
  'Size': 711111292,
  'VirtualSize': 711111292},
 {'Created': 1468851596,
  'Id': 'sha256:4f8313e22b69cd0f4d2469b9504003649563feaf9c5b32b7b26d7889318603e5',
  'Labels': {},
  'ParentId': '',
  'RepoDigests': ['108747154147.dkr.ecr.eu-west-1.amazonaws.com/life.organised@sha256:8f64bf8ba55c2baa50370e1ca4b9ca827f3e334714d6a628680a2697c0549e97'],
  'RepoTags': None,
  'Size': 709676802,
  'VirtualSize': 709676802}]
Traceback (most recent call last):
  File "/Users/kenpay/Projects/life_organiser/venv3/bin/shipwright", line 11, in <module>
    sys.exit(main())
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/cli.py", line 170, in main
    environ=os.environ,
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/cli.py", line 243, in run
    for event in events:
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/base.py", line 22, in _build
    for evt in build.do_build(self.docker_client, this_ref_str, targets):
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/build.py", line 42, in do_build
    for evt in build(client, parent_ref, target):
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/build.py", line 63, in build
    built_tags = docker.last_built_from_docker(client, image.name)
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py", line 30, in last_built_from_docker
    return list([x for i in images for x in key_from_image_info(i)])
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py", line 30, in <listcomp>
    return list([x for i in images for x in key_from_image_info(i)])
  File "/Users/kenpay/Projects/life_organiser/venv3/lib/python3.5/site-packages/shipwright/docker.py", line 23, in key_from_image_info
    return [key_from_image_name(t) for t in image_info_dict['RepoTags']]
TypeError: 'NoneType' object is not iterable

**Comment by graingert** [comment]
Get RepoTags is None not an empty list

**Comment by graingert** [comment]
@kgpayne You need to run `docker rmi 108747154147.dkr.ecr.eu-west-1.amazonaws.com/life.organised@sha256:8f64bf8ba55c2baa50370e1ca4b9ca827f3e334714d6a628680a2697c0549e97`

**Comment by graingert** [comment]
@kgpayne try v0.5.0
