### ISSUE TITLE
Whenever I try to run shipwright it throws the following error

### ISSUE THREAD

**Issue by nw0428** [6si/shipwright#8]
shipwright shipwright
Traceback (most recent call last):
  File "/usr/bin/shipwright", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.2.1

**Comment by tya** [comment]
@srobertson can consider adding the Dockerfile to create sixsense/shipwright to this repo?
