### ISSUE TITLE
Random-ish 'raise JSONDecodeError("Extra data", s, end) error during building'

### ISSUE THREAD

**Issue by spkane** [6si/shipwright#83]
While trying to get shipwright working for the first time, I am finding that builds consistently fail at a semi random spot it the build with an error similar to this:

```
Traceback (most recent call last):
  File "/Users/skane/virtualenvs/default-3.5/bin/shipwright", line 11, in <module>
    sys.exit(main())
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/cli.py", line 183, in main
    new_style_args=arguments,
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/cli.py", line 270, in run
    for event in events:
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/base.py", line 25, in _build
    for evt in build.do_build(client, ref, targets, pull_cache):
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/build.py", line 42, in do_build
    for evt in build(client, parent_ref, target, pull_cache):
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/build.py", line 96, in build
    yield process_event_(evt)
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/build.py", line 60, in process_event_
    evt_parsed = json_loads(evt)
  File "/Users/skane/virtualenvs/default-3.5/lib/python3.5/site-packages/shipwright/compat.py", line 15, in json_loads
    return json.loads(s, **kwargs)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 106)
```

Sometimes this is almost immediately and sometimes this is a few steps into the Dockerfile.

Our registry is running a current release for Docker Distribution, and I am using the Docker for Mac client at the moment (Docker 1.12).

```
# cat .shipwright.json
{
  "version": 1.0,
  "namespace": "cf-registry.example.net"
}

# python --version
Python 3.5.2

# pip list
docker-py (1.9.0)
gitdb (0.6.4)
GitPython (2.0.8)
pip (8.1.2)
requests (2.11.1)
setuptools (18.0.1)
shipwright (0.6.3)
six (1.10.0)
smmap (0.9.0)
websocket-client (0.37.0)
wheel (0.24.0)
```

**Comment by graingert** [comment]
Sounds like a bug in docker-py, 

Can you work out what string is failing to parse?

**Comment by spkane** [comment]
I haven't yet. But I'll try and dig into it a bit this week and update the ticket.

**Comment by graingert** [comment]
@spkane I think this will be fixed in docker-py 1.10

**Comment by spkane** [comment]
Great. I will try to keep an eye out and try to test it when it lands (and time allows)

**Comment by dayer4b** [comment]
looks like 1.10 has been out since September 9.  they're up to 1.10.5 now.  has anybody tried this?

this bug is stopping me from using shipwright
