### ISSUE TITLE
Using --pull-cache causes a NotFound exception for missing tags if DOCKER_HOST is set.

### ISSUE THREAD

**Issue by acaprez** [6si/shipwright#95]
Hello,

We use Shipwright within a docker-in-docker configuration to build/push our images.  With that setup, `DOCKER_HOST` is set and points to the tcp address of the dind container.  It seems the Docker Python library behaves differently in that case versus when using `/var/run/docker.sock` locally.  When doing a `docker.APIClient.pull()` and the tag isn't present, it returns a `docker.errors.NotFound` exception instead of a JSON object, and causes Shipwright to die.  See for example this traceback:

```
 /singularity-dockerfiles # shipwright build --pull-cache
/usr/lib/python2.7/site-packages/docker/api/client.py:147: UserWarning: The minimum API version supported is 1.21, but you are using version 1.18. It is recommended you either upgrade Docker Engine or use an older version of Docker SDK for Python.
  'Python.'.format(MINIMUM_DOCKER_API_VERSION, self._version)
Traceback (most recent call last):
  File "/usr/bin/shipwright", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/shipwright/cli.py", line 223, in main
    new_style_args=arguments,
  File "/usr/lib/python2.7/site-packages/shipwright/cli.py", line 331, in run
    for event in events:
  File "/usr/lib/python2.7/site-packages/shipwright/base.py", line 24, in _build
    for evt in build.do_build(client, ref, targets, self._cache):
  File "/usr/lib/python2.7/site-packages/shipwright/build.py", line 43, in do_build
    for evt in build(client, parent_ref, target, cache):
  File "/usr/lib/python2.7/site-packages/shipwright/build.py", line 68, in build
    for evt in cache.pull_cache(image):
  File "/usr/lib/python2.7/site-packages/shipwright/cache.py", line 54, in pull_cache
    stream=True,
  File "/usr/lib/python2.7/site-packages/docker/api/image.py", line 345, in pull
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 208, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found for url: http://unlhcc__docker:2375/v1.18/images/create?tag=fc2c5a5a0b7b&fromImage=unlhcc%2Fcuda-ubuntu ("manifest for unlhcc/cuda-ubuntu:fc2c5a5a0b7b not found")
```

I've written a fix that catches the `NotFound` exception and raises a `CacheMissException` to behave the same as when JSON is returned indicating the tag is missing.  I'd be happy to open a PR if that would be useful.

**Comment by graingert** [comment]
Yep, that would be handy. Can you also raise the relevant issues And PR for docker-py?

**Comment by acaprez** [comment]
Sure - PR is created.  A little searching found [this PR](https://github.com/docker/docker-py/pull/676) for docker-py, so that seems to be the intended behavior.  I'm not sure why it doesn't behave the same using a local Docker then.

**Comment by graingert** [comment]
@shin- is this expected behaviour from docker-py?
